#ifndef __CULIP_CUBLAS_HPP__
#define __CULIP_CUBLAS_HPP__

enum CULiP_cublas_control_t {
	// LEVEL 2
	CULiP_cublasDgemv,
	CULiP_cublasSgemv,
	CULiP_cublasCgemv,
	CULiP_cublasZgemv,
	CULiP_cublasDgbmv,
	CULiP_cublasSgbmv,
	CULiP_cublasCgbmv,
	CULiP_cublasZgbmv,
	CULiP_cublasDger,
	CULiP_cublasSger,
	CULiP_cublasCgeru,
	CULiP_cublasCgerc,
	CULiP_cublasZgeru,
	CULiP_cublasZgerc,
	CULiP_cublasDsbmv,
	CULiP_cublasSsbmv,
	CULiP_cublasDspmv,
	CULiP_cublasSspmv,

	// LEVEL 3
	CULiP_cublasDgemm,
	CULiP_cublasSgemm,
	CULiP_cublasHgemm,
	CULiP_cublasCgemm,
	CULiP_cublasZgemm,
	CULiP_cublasGemmEx,
	CULiP_cublasCgemm3m,
	CULiP_cublasZgemm3m,
	CULiP_cublasDgemmBatched,
	CULiP_cublasSgemmBatched,
	CULiP_cublasHgemmBatched,
	CULiP_cublasCgemmBatched,
	CULiP_cublasZgemmBatched,
	CULiP_cublasGemmBatchedEx,
	CULiP_cublasDgemmStridedBatched,
	CULiP_cublasSgemmStridedBatched,
	CULiP_cublasHgemmStridedBatched,
	CULiP_cublasCgemmStridedBatched,
	CULiP_cublasZgemmStridedBatched,
	CULiP_cublasGemmStridedBatchedEx,
	CULiP_cublasDsyrk,
	CULiP_cublasSsyrk,
	CULiP_cublasCsyrk,
	CULiP_cublasZsyrk,
	CULiP_cublasDsymm,
	CULiP_cublasSsymm,
	CULiP_cublasCsymm,
	CULiP_cublasZsymm,
	CULiP_cublasDsyr2k,
	CULiP_cublasSsyr2k,
	CULiP_cublasCsyr2k,
	CULiP_cublasZsyr2k,
	CULiP_cublasDsyrkx,
	CULiP_cublasSsyrkx,
	CULiP_cublasCsyrkx,
	CULiP_cublasZsyrkx,
	CULiP_cublasDtrmm,
	CULiP_cublasStrmm,
	CULiP_cublasCtrmm,
	CULiP_cublasZtrmm,
	CULiP_cublasDtrsm,
	CULiP_cublasStrsm,
	CULiP_cublasCtrsm,
	CULiP_cublasZtrsm,
	CULiP_cublasDtrsmBatched,
	CULiP_cublasStrsmBatched,
	CULiP_cublasCtrsmBatched,
	CULiP_cublasZtrsmBatched,
	CULiP_cublasChemm,
	CULiP_cublasZhemm,
	CULiP_cublasCherk,
	CULiP_cublasZherk,
	CULiP_cublasCher2k,
	CULiP_cublasZher2k,
	CULiP_cublasCherkx,
	CULiP_cublasZherkx,
	CULiP_cublas_enum_length
};

extern "C" void CULiP_enable_cublas_profiling(const CULiP_cublas_control_t target_function);
extern "C" void CULiP_disable_cublas_profiling(const CULiP_cublas_control_t target_function);
extern "C" void CULiP_enable_cublas_all_profiling();
extern "C" void CULiP_disable_cublas_all_profiling();
#endif
